openapi: 3.0.0
info:
  title: New Collection
  version: 1.0.0
servers:
  - url: https://nrn--mvc4.sandbox.my.salesforce.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /services/apexrest/notifications/:
    post:
      tags:
        - default
      summary: notification details post insert
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Parent Notification 222
                message: Holds child notifications 222
                opportunity: 0069p00000F9NMXAA3
                contact: 0039p00000SyJ7hAAF
                type: Notification
                status: Pending
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}